# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# Disable space inside array literal brackets rule
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Prefer single quotes unless interpolation or escaping is needed
Style/StringLiterals:
  EnforcedStyle: single_quotes
